USE qly;

-- Bảng Khách Hàng
CREATE TABLE IF NOT EXISTS khachhang (
  MaKH VARCHAR(50) PRIMARY KEY,
  HoTen VARCHAR(100) NOT NULL,
  CMND VARCHAR(20) NOT NULL,
  DienThoai VARCHAR(20) NOT NULL
);

-- Bảng Phòng
CREATE TABLE IF NOT EXISTS phong (
  PhongSo VARCHAR(20) PRIMARY KEY,
  LoaiPhong VARCHAR(50) NOT NULL,
  GiaPhong INT NOT NULL,
  TinhTrang VARCHAR(20) DEFAULT 'trong'
);

-- Bảng Dịch Vụ
CREATE TABLE IF NOT EXISTS dichvu (
  MaDV VARCHAR(20) PRIMARY KEY,
  TenDV VARCHAR(100) NOT NULL,
  GiaDV INT NOT NULL
);


-- 4. Bảng Đặt Phòng
CREATE TABLE IF NOT EXISTS datphong (
  PhongSo VARCHAR(20) NOT NULL,
  MaKH VARCHAR(50) NOT NULL,
  NgayDat DATETIME NOT NULL,
  NgayNhan DATE NOT NULL,
  NgayTra DATE NOT NULL,
  SoNguoi INT,
  TinhTrang VARCHAR(20) DEFAULT 'dadat'
);

-- 5. Bảng Sử Dụng Dịch Vụ
CREATE TABLE IF NOT EXISTS sudungdv (
  MaSD INT AUTO_INCREMENT PRIMARY KEY,
  PhongSo VARCHAR(20) NOT NULL,
  MaDV VARCHAR(20) NOT NULL,
  SoLuong INT NOT NULL,
  NgayNhan DATE NOT NULL,
  NgayTra DATE NOT NULL
);

-- 6. Bảng Hóa Đơn
CREATE TABLE IF NOT EXISTS hoadon (
  MaHD VARCHAR(50) PRIMARY KEY,
  PhongSo VARCHAR(20) NOT NULL,
  NgayNhan DATE NOT NULL,
  NgayTra DATE NOT NULL,
  PhuongThucTT VARCHAR(50) NOT NULL,
  TongDV INT DEFAULT 0,
  TongTien INT DEFAULT 0
);